name: practice
services:
    db:
        image: postgres:latest
        environment:
            POSTGRES_DB: practice_db
            POSTGRES_USER: your_username
            POSTGRES_PASSWORD: your_password
            POSTGRES_HOST_AUTH_METHOD: trust
        ports:
            - "5434:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U your_username -d practice_db"]
            interval: 5s
            timeout: 5s
            retries: 10

    movies:
        container_name: movies
        image: movies
        ports:
            - "8000:8000"
        environment:
            DATABASE_URL: postgresql+psycopg2://your_username:your_password@db:5432/practice_db
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
            interval: 30s
            timeout: 10s
            retries: 3
        depends_on:
            db:
                condition: service_healthy

    users:
        container_name: users
        image: users
        ports:
            - "8001:8001"
        environment:
            DATABASE_URL: postgresql+psycopg2://your_username:your_password@db:5432/practice_db
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8001/health" ]
            interval: 30s
            timeout: 10s
            retries: 3
        depends_on:
            db:
                condition: service_healthy